name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
      env:
        VITE_ADMIN_LOGIN: ${{ secrets.ADMIN_LOGIN }}
        VITE_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
